source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/stackJolin/STSpec.git'

platform :osx, '10.13'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'UnPackCar' do
#  pod 'OSXUIKit', :path => "../../OSXUIKit"
#  pod 'OSXCoreKit', :path => "../../OSXCoreKit"
#  pod 'OSXAlert', :path => "../../OSXAlert"
  pod 'OSXAlert', "1.1.1"
  pod 'OSXUIKit', "1.1.2"
  pod 'OSXCoreKit', "1.1.2"
  pod 'Masonry'
  pod 'CocoaLumberjack'
end
