source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/stackJolin/OSXCoreKit.git'

platform :osx, '10.13'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'UnPackCar' do
#  pod 'OSXUIKit', :path => "../../OSXUIKit"
#  pod 'OSXCoreKit', :path => "../../OSXCoreKit"
  pod 'OSXUIKit', "1.1.1"
  pod 'OSXCoreKit', "1.1.1"
  pod 'Masonry'
  pod 'CocoaLumberjack'
end
